[project]
name = "AiDM-trial"
version = "0.1.0"
description = "AiDM Trial for generating FS from Code"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.117.1",
    "mrkdwn-analysis>=0.1.6",
    "uvicorn>=0.37.0",
]
