[project]
name = "code-to-code"
version = "0.1.0"
description = "Test from Code to DTD"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "isort>=7.0.0",
    "mrkdwn-analysis>=0.1.6",
    "pexpect>=4.9.0",
]
