[project]
name = "moneynote-api"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "pydantic-settings",
    "python-jose[cryptography]",
    "passlib[bcrypt]",
    "pytest",
    "httpx",
    "pyjwt",
]
